### ISSUE TITLE
Error: unable to process file: gossos.mp3 with exception 'max() iterable argument is empty'

### ISSUE THREAD

**Issue by homocomputeris** [Softcatala/whisper-ctranslate2#106]
```shell
whisper-ctranslate2 gossos.mp3 --model medium
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████| 2.26k/2.26k [00:00<00:00, 15.5MB/s]
vocabulary.txt: 100%|████████████████████████████████████████████████████████████████████████████████████| 460k/460k [00:00<00:00, 952kB/s]
tokenizer.json: 100%|█████████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 3.06MB/s]
model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████| 1.53G/1.53G [01:11<00:00, 21.3MB/s]
Error: unable to process file: gossos.mp3 with exception 'max() iterable argument is empty'
```

**Comment by jordimas** [comment]
Can you please try again with version 0.46? 

Do:

pip install whisper-ctranslate2==0.4.6

This version has more logging on the errors. Thanks

**Comment by homocomputeris** [comment]
```shell
user@box ~/Recordings % whisper-ctranslate2 gossos.mp3 --model base
Detecting language using up to the first 30 seconds. Use `--language` to specify the language
config.json: 100%|██████████████████████████████████████████████████████████████████████████████████| 2.31k/2.31k [00:00<00:00, 13.3MB/s]
vocabulary.txt: 100%|█████████████████████████████████████████████████████████████████████████████████| 460k/460k [00:00<00:00, 1.15MB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████| 2.20M/2.20M [00:00<00:00, 3.43MB/s]
model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████| 145M/145M [00:04<00:00, 30.5MB/s]
Error: Unable to process file: gossos.mp3
Exception Type: ValueError████████████████████████████████████████████████████████████████████████████| 145M/145M [00:04<00:00, 35.0MB/s]
Exception Message: max() iterable argument is empty
Traceback:
Traceback (most recent call last):
  File "/home/user/.rye/tools/whisper-ctranslate2/lib/python3.12/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 240, in main
    result = transcribe.inference(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.rye/tools/whisper-ctranslate2/lib/python3.12/site-packages/src/whisper_ctranslate2/transcribe.py", line 131, in inference
    segments, info = self.model.transcribe(
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.rye/tools/whisper-ctranslate2/lib/python3.12/site-packages/faster_whisper/transcribe.py", line 419, in transcribe
    language = max(
               ^^^^
ValueError: max() iterable argument is empty

Transcription results written to '/home/user/Recordings' directory
```

```shell
user@box ~/Recordings % whisper-ctranslate2 --language ca gossos.mp3 --model base
Detected language 'Catalan' with probability 1.000000
Transcription results written to '/home/user/Recordings' directory
user@box ~/Recordings % cat gossos.txt
user@box ~/Recordings % cat gossos.srt
cat gossos.vtt
WEBVTT
```

**Comment by homocomputeris** [comment]
Ok, now I suspect that the file may be damaged on my side.

**Comment by homocomputeris** [comment]
Yeah, sorry, it seems that the files failed to download correctly.
