### ISSUE TITLE
argument error when doing vad_filter

### ISSUE THREAD

**Issue by asafarevich** [Softcatala/whisper-ctranslate2#48]
```
whisper-ctranslate2 --live_transcribe True --language en --device cpu --model small --vad_filter True
```
It will listen, but when it comes to transcribing it will crash with this error
```
Traceback (most recent call last):
  File "/home/hackerman/anaconda3/envs/whisper/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 498, in main
    Live(
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/src/whisper_ctranslate2/live.py", line 163, in inference
    self.listen()
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/src/whisper_ctranslate2/live.py", line 159, in listen
    self.process()
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/src/whisper_ctranslate2/live.py", line 134, in process
    result = self.transcribe.inference(
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/src/whisper_ctranslate2/transcribe.py", line 128, in inference
    segments, info = self.model.transcribe(
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/faster_whisper/transcribe.py", line 252, in transcribe
    speech_chunks = get_speech_timestamps(audio, vad_parameters)
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/faster_whisper/vad.py", line 94, in get_speech_timestamps
    speech_prob, state = model(chunk, state, sampling_rate)
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/faster_whisper/vad.py", line 288, in __call__
    out, h, c = self.session.run(None, ort_inputs)
  File "/home/hackerman/anaconda3/envs/whisper/lib/python3.9/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 217, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(double)) , expected: (tensor(float))
```

**Comment by jordimas** [comment]
This should be fixed in version 0.2.7 just released. Thanks for reporting
