### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Morv55555** [Softcatala/whisper-ctranslate2#74]
I've been using it on google colab and it worked perfect but recently I get the following error message. what has changed?

Traceback (most recent call last):
  File "/usr/local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 547, in main
    result = transcribe.inference(
  File "/usr/local/lib/python3.10/dist-packages/src/whisper_ctranslate2/transcribe.py", line 170, in inference
    for segment in segments:
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 941, in restore_speech_timestamps
    for segment in segments:
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 445, in generate_segments
    encoder_output = self.encode(segment)
  File "/usr/local/lib/python3.10/dist-packages/faster_whisper/transcribe.py", line 629, in encode
    return self.model.encode(features, to_cpu=to_cpu)
RuntimeError: Library libcublas.so.11 is not found or cannot be loaded

**Comment by TasseDeCafe** [comment]
Hi, did you figure this out? Getting the same error.

**Comment by Morv55555** [comment]
Yeah, you need to downgrade cudas to libcublas 11. Just copy the code below after the usual install:
!sudo apt-get install libcublas11

**Comment by TasseDeCafe** [comment]
Thank you!

**Comment by Volbla** [comment]
I faced the same problem (after getting a hold of cudnn and zlibwapi), but the solution turned out to be really simple.

Cublas is bundled with cuda. The file just has a different name depending on the version. I can't use cuda 11 because that's when they stopped supporting windows 7. So instead i just made a copy of `cublas64_10.dll` and renamed it to `cublas64_11.dll`

I don't know where this file is imported/used, but it seems weird to have a seemingly hardcoded filename instead of just, idk, letting cuda fetch its own library?
