### ISSUE TITLE
fail safe if no audio available

### ISSUE THREAD

**Issue by drzraf** [Softcatala/whisper-ctranslate2#96]
1. If a video contains no audio (video-only mp4), the following errors arises:
```
Traceback (most recent call last):
  File "/home/.local/bin/whisper-ctranslate2", line 8, in <module>
    sys.exit(main())
  File "/home/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/whisper_ctranslate2.py", line 231, in main
    result = transcribe.inference(
  File "/home/.local/lib/python3.10/site-packages/src/whisper_ctranslate2/transcribe.py", line 131, in inference
    segments, info = self.model.transcribe(
  File "/home/.local/lib/python3.10/site-packages/faster_whisper/transcribe.py", line 318, in transcribe
    audio = decode_audio(audio, sampling_rate=sampling_rate)
  File "/home/.local/lib/python3.10/site-packages/faster_whisper/audio.py", line 52, in decode_audio
    for frame in frames:
  File "/home/.local/lib/python3.10/site-packages/faster_whisper/audio.py", line 103, in _resample_frames
    for frame in itertools.chain(frames, [None]):
  File "/home/.local/lib/python3.10/site-packages/faster_whisper/audio.py", line 90, in _group_frames
    for frame in frames:
  File "/home/.local/lib/python3.10/site-packages/faster_whisper/audio.py", line 80, in _ignore_invalid_frames
    yield next(iterator)
  File "av/container/input.pyx", line 207, in decode
  File "av/container/input.pyx", line 140, in demux
  File "av/container/streams.pyx", line 116, in av.container.streams.StreamContainer.get
IndexError: tuple index out of range
```

This is particularly painful if it's been run to transcribe dozens of videos because it breaks the whole process.

2. To make the things more annoying, `whisper-ctranslate2` cli has no way to _resume_ (not overriding already existing transcription) what means there is no (obvious) way to recover from the above interruption (without redoing the same work again and again)

I suggest to:
A. Skip unsuitable file cleanly with a warning
B. Add a flag to skip over existing file in the output-directory without redoing the work nor overriding them.

**Comment by jordimas** [comment]
Hello. Can you provide a link or attach here a sample file that breaks the tool this way? Thanks

**Comment by drzraf** [comment]
Just a mp4 with no audio track.

https://github.com/Softcatala/whisper-ctranslate2/assets/1169926/ca160a0a-9b88-4c14-b885-e036ee73d065

**Comment by jordimas** [comment]
Thanks, this is fixed in version 0.44 or higher.
